# Generated by Django 5.2.1 on 2025-05-29 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'page',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'size',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='scrapers.category')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('product_class', models.CharField(db_column='class', max_length=100)),
                ('model_code', models.CharField(blank=True, max_length=100, null=True)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('link', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scrapers.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scrapers.category')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('price_current', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_prev', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('free_shipping', models.BooleanField(default=False)),
                ('currency', models.CharField(max_length=10)),
                ('recorded_at', models.DateTimeField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricings', to='scrapers.page')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricings', to='scrapers.product')),
            ],
            options={
                'db_table': 'pricing',
            },
        ),
        migrations.CreateModel(
            name='ProductPage',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cuotas', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_info', models.TextField(blank=True, null=True)),
                ('shipping_info', models.TextField(blank=True, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='scrapers.page')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='scrapers.product')),
            ],
            options={
                'db_table': 'product_page',
            },
        ),
        migrations.CreateModel(
            name='ProductQuota',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('payment_method', models.CharField(max_length=100)),
                ('quota_count', models.IntegerField()),
                ('price_per_quota', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_free', models.BooleanField(default=False)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='scrapers.page')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='scrapers.product')),
            ],
            options={
                'db_table': 'product_quota',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('variant_type', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='scrapers.product')),
            ],
            options={
                'db_table': 'product_variant',
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('available', models.IntegerField()),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='scrapers.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='scrapers.size')),
            ],
            options={
                'db_table': 'product_size',
            },
        ),
    ]
