# Generated by Django 5.2.1 on 2025-06-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0002_alter_brand_id_alter_brand_name_alter_category_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodesDexter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('provider_code', models.CharField(blank=True, max_length=100, null=True)),
                ('dexter_code', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'dexter_code',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='provider_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
