[packages]
chromium = "*"
chromium-chromedriver = "*"
libX11 = "*"
libXcomposite = "*"
libXcursor = "*"
libXdamage = "*"
libXext = "*"
libXi = "*"
libXtst = "*"
libxrandr = "*"
libXrender = "*"
libxss = "*"
libxcursor = "*"
nss = "*"
dbus-glib = "*"
gtk3 = "*"
fontconfig = "*"
