[tool.nixpacks]
start-command = "gunicorn scraper_project.wsgi:application --bind 0.0.0.0:$PORT"

[packages]
# El navegador Chromium y el driver
chromium = "*"
chromium-chromedriver = "*"

# Paquetes nativos que Chromium y ChromeDriver requieren
libX11 = "*"
libXcomposite = "*"
libXcursor = "*"
libXdamage = "*"
libXext = "*"
libXi = "*"
libXtst = "*"
libxrandr = "*"
libXrender = "*"
libxss = "*"
nss = "*"
fontconfig = "*"
gtk3 = "*"
dbus-glib = "*"
