[tool.nixpacks]
start-command = "gunicorn scraper_project.wsgi:application --bind 0.0.0.0:$PORT"

[tool.nixpacks.packages]
python = "*"
# if you need chromium for other reasons, you can also install it via Nixpacks:
chromium               = "*"
chromium-chromedriver  = "*"

# …any other native libs you need can go here (e.g. libX11, fontconfig, etc.)

# Now, a custom “chromium” phase that runs playwright’s installer:
[tool.nixpacks.phases.chromium]
dependsOn = ["install"]
cmds = [
  "playwright install --with-deps chromium"
]
