[tool.nixpacks]
start-command = "gunicorn scraper_project.wsgi:application --bind 0.0.0.0:$PORT"

[tool.nixpacks.packages]
chromium = "*"
chromium-chromedriver = "*"

libX11 = "*"
libXcomposite = "*"
libXcursor = "*"
libXdamage = "*"
libXext = "*"
libXi = "*"
libXtst = "*"
libxrandr = "*"
libXrender = "*"
libxss = "*"
nss = "*"
fontconfig = "*"
gtk3 = "*"
dbus-glib = "*"
