[tool.nixpacks]
start-command = "gunicorn scraper_project.wsgi:application --bind 0.0.0.0:$PORT"

[tool.nixpacks.packages]
python                 = "*"
chromium               = "*"
chromium-chromedriver  = "*"
nodejs                  = "*"
npm                     = "*"

[tool.nixpacks.phases.chromium]
dependsOn = ["install"]
cmds = [
  "npm i -g playwright", 
  "playwright install --with-deps chromium"
]
