[tool.nixpacks]
start-command = "gunicorn scraper_project.wsgi:application --bind 0.0.0.0:$PORT"

[tool.nixpacks.packages]
python                 = "*"
chromium               = "*"
chromium-chromedriver  = "*"
gcc                    = "*"
gcc-libs               = "*"

[tool.nixpacks.phases.chromium]
dependsOn = ["install"]
cmds = [
  "python3 -m playwright install --with-deps chromium"
]
